name: 构建发布

on:
  workflow_dispatch:
    inputs:
      mark:
        description: 发布说明
        required: true
        default: ''
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 构建发布
    runs-on: ubuntu-latest
    steps:
      - name: 环境配置
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: 发布说明
        run: |
          echo "${{ github.event.inputs.mark }}"

      - name: 打包
        run: |
          cd web-src
          pnpm install
          npm run build

      - name: 发布
        run: |
          cd ..
          npm install -g npm@latest
          npm publish
